{
  "hash": "c1a69822bd52f65352658e8f22f7c90f",
  "result": {
    "markdown": "# Innlesning av data med innebygd metadata\n\nI dette kapittelet skal vi bruke følgende pakker:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)       # Importere data fra SAS, SPSS og Stata\nlibrary(tidyverse)   # Pakker for generell datahåndtering og grafikk\nlibrary(labelled)    # Håndtering av variable med labler, importert fra annen software\nlibrary(forcats)     # Lettere omkoding av faktorvariable\n```\n:::\n\n\n\nDet kan være ulike problemstillinger knyttet til type data, dataformater, men også hvordan noen har valgt å lagre/distribuere data. Det kan være vanskelig å skille mellom disse og man kan noen ganger lure på om det er hos R begrensningene ligger. Det kan være flere av disse, men som hovedregel er problemet at data ofte ikke er distribuert i et universelt format. Permanent lagring og distribusjon av data er krevende, men ikke temaet her. Uansett: du vil ofte få data i et format som ikke er tilrettelagt verken i eller for R. Å gjøre om data fra et format til et annet kan være en avgjørende oppgave for å få gjort noe som helst. \n\nDette kan være krøkete og du har virkelig muligheten til å kløne det til skikkelig. For at du skal slippe det gir dette kapittelet en oppskrift for å håndtere slike data slik at du kan jobbe videre med dem i R på en hensiktsmessig måte. \n\n\nI Norge er Sikt (tidliger NSD) en stor leverandør av data til samfunnsvitenskapen. De leverer ofte data i proprietære formater som SAS, SPSS eller Stata. I tillegg vil de levere en *flat fil* som typisk er *comma separated variables* (csv). I de førstnevnte vil metadata være integrert, mens i csv er det bare kodene og metadata må slås opp i dokumentasjonen. \n\n\nDet er også noen utfordringer i R for håndtering av factor-variable med lange (noen ganger veldig lange) 'labler'. Det gis noen løsninger på det også som gjør kodingen håndterbar. \n\n\n## Løsning: Fiks alt i en fei\nFor å gjøre en lang historie kort, så trenger vi å fikse en del ting når vi leser inn data fra formater som Stata, SPSS og SAS. Det er primært knyttet til hvordan metadata kan være integrert i disse dataformatene. Den etterfølgende koden fikser følgende for *hele* datasettet, og eksempelet er ved bruk av NorLAG-dataene: \n\n1) Lese inn data fra Stataformat (linje 1)\n1) Gjøre om koder som indikerer spesielle missing-verdier til NA (linje 2.4)\n1) Fjerne de nå ubrukte label-nivåene (jf. forrige punkt) (linje 5)\n1) Gjøre om alle labelled-variable til factor (linje 6)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag <- read_stata(\"data/norlag_panel2022.dta\") %>% \n    mutate(across( where(is.labelled) ,  ~replace(., \n                                        . %in% c(997, 998, 999, 99999, 999999), \n                                        NA))) %>%\n  # For hele datasettet fjernes ikke-brukte labler \n  drop_unused_value_labels() %>% \n  # Så gjør alle variable om til mer ordinære R-format. Dvs. gjøre labler om til factor\n  unlabelled()\n```\n:::\n\n\nKoden ovenfor kan være litt vanskelig å tolke for den uerfarne, og logikken forklares i det etterfølgende. For datasettet bør det finnes en dokumentasjon som forklarer hvilke verdier som indikerer *missing*, som i tilfellet med NorLAG er verdiene 997, 998, 999, 99999 og 999999. Når disse verdiene er angitt, så gjøres datasettet om til et hensiktsmessig R-format. \n\n\n\n\n## Dataformater og metadata\nEn type data som er mye brukt i samfunnsvitenskapen er surveydata, altså: data innhentet ved hjelp av spørreskjema. Slike data inneholder gjerne en god del kategoriske data eller man svarer på en likert-skala (f.eks. skala fra 1 til 5), men også kontinuerlige variable og kan også være tekstsvar. \n\nSlike data er ofte *kodet* slik at bestemte verdier har en tekstlig betydning. F.eks. 1 = \"gift\" og 2 = \"ugift\", eller 1 = \"veldig fornøyd\" og 5 = \"veldig misfornøyd\" osv. \n\nI R vil slike variable normalt håndteres som såkalte faktor-variable, men ofte vil surveydata inneholde relativt lange tekstverdier som gjør det tungvint. Men det finnes løsninger. For å gjøre en lang historie kort: Surveydata er best å håndtere med pakkene {labelled}. For videre analyser er det derimot vanligvis best å ha faktor-variable, så vi vil oftest konvertere dataene etterpå. Det høres tungvindt ut, men konverteringen er bare et par linjer kode. \n\nEt spesielt problem er at i Stata og SPSS vil mange datasett inneholde spesielle verdier som skal tolkes som *manglende data*, såkalt 'missing'. Det kan altså være egne koder for om respondenten ikke fikk stilt spørsmålet, ikke ville svare, eller andre grunner. For en variabel for inntekt kan f.eks. verdien 999999 betyr at vedkommende ikke ville svare. Når vi regner et gjennomsnitt er det da viktig at akkurat disse verdiene ikke inngår i beregningen. (Å kode på denne måten kan si er en uting uansett software, så vi skal i hvert fall kvitte oss med disse). \n\nI R er det flere pakker og funksjoner som er spesielt egnet til å håndtere slike data og vi bruker følgende: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)       # For å lese inn data fra SPSS, Stata eller SAS\nlibrary(labelled)    # For å håndtere variable og verdier som inneholder 'labler'\n```\n:::\n\n\nI tillegg skal vi bruke pakker for generell datahåndtering som er samlet i pakken {tidyverse}, deriblant en pakke {forcats} for håndtering av kategoriske variable. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)   # Generelle funksjoner for datahåndtering\nlibrary(forcats)     # Funksjoner spesielt for factor-variable\n```\n:::\n\n\n\nI det følgende skal vi dekke disse temaene: \n\n* Hvordan lese inn data fra Stata-formatet\n* Hvordan få oversikt over datasettet\n* Hvordan omkode variable med 'labler' \n* Hvordan håndtere verdier som er kodet som 'missing' i Stata-formatet (kalles user-defined-NA i R) \n* Hvordan gjøre om labelled-variable til faktor-variable \n* Hvordan gjør det ovenstående på veldig mange variable på en gang (altså: fremfor en og en, så du kan bruke tiden din på morsommere ting)\n\n\n\n### Lese inn data i Stata-formatet .dta \nI det følgende bruker jeg som eksempel dataene NorLag som man kan få tilgang til via NSD/Sikt her: https://norlag.nsd.no/. Disse dataene kan lastes ned i flere ulike typer formater slik data fra NSD/Sikt gjerne kan. Tilsvarende vil altså gjelde for andre datasett derfra. De ulike dataformatene er typisk tilpasset spesifikke software og det er en utfordring hvis man bruker et annet system enn det NSD har sett for seg. \n\nDe leverer også data i csv-format som ikke er uavhengig av software og kan leses inn av alle typer statistikksoftware. Generelt er csv-formatet å foretrekke når man skal dele data nettopp av denne grunn. Det er også et format som ikke er sårbar for endringer i softwaren over lengre tid slik at det må konverteres mellom formatversjoner. Særlig for surveydata er derimot csv-formatet ikke alltid så godt i praksis da det krever en godt opplegg for dokumentasjon og metadata som trengs i kodingen av data. NSD/Sikt har valgt en måte å dokumentere metadata på som ikke er lett håndterbart maskinelt av ikke-profesjonelle programmerere. Dette gjør csv-formatet lite egnet i dette tilfellet. \n\nDerimot kan man laste ned dataene i formatene til SPSS eller Stata. Vi vil her forholde oss kun til Stata-filer, men det vil være tilsvarende med SPSS og i praksis også SAS. Stata-formatet har en filhale som slutter på '.dta'. Fordelen med dette formatet er at metadata er innebygd i selve dataformatet. Altså, at en kategorisk variabel vil inneholde *både* en tallkode og en tekst med informasjon om hva tallet betyr. Dette er imidlertid en måte å håndtere data på som ikke er optimal for R. \n\nI det følgende skal vi dekke \n\n* Lese inn Stata-filer \n* Søke etter variable \n* Undersøke hvordan variable er kodet, se på 'lablene'\n* Gjøre omkodinger av variablene\n* Endre variable til faktor-variable \n* Omkode faktor-variable med veldig lange tekstverdier \n\n\n### Innlesning med {haven}\nFormatene Stata, SPSS og SAS er proprietære og man trenger i utgangspunktet disse softwarene for å åpne datafilene (og betale dyr lisens). For å lese inn i R kan man bruke pakken {haven} som inneholder spesialiserte funksjoner for å lese inn disse formatene. Funksjonen `read_stata()` leser inn dataene på en måte som bevarer særegenhetene fra Stata-formatet. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag <- read_stata(\"data/norlag_panel2022.dta\") \n```\n:::\n\n\n\n\n## Få oversikt over dataene \nVi har nå et datasett i minnet og vi bør ta en titt på det. Nå er det mange hundre variable i datasettet, så det er lite hensiktsmessig å printe det til konsollen fordi det er rett og slett ikke plass. I tidligere kurs skal dere ha lært å bruke funksjonen *glimpse()*, men også her blir det mest rotete fordi det er så mange variable. \n\nEn enkel løsning er å bare se på noen få variable om gangen. Med klammeparentes kan vi angi hvilke radnummer og kolonnenummer vi ønsker se på med følgende syntax: **datasett[rader, kolonner]** der altså komma skiller mellom rader og kolonner. Følgende eksempel viser hvordan man kan bruke *head()* for å vise de første observasjonene i datasettet med bare de første 5 variablene (altså: kollonne nr 1-5). \n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(norlag[, 1:5])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  ref_nr round iointervjumnd                 iointervjuyr ioalder               \n   <dbl> <dbl> <dbl+lbl>                     <dbl+lbl>    <dbl+lbl>             \n1      5     1      5                          2002           68                \n2      5     2     11                          2007           72                \n3      5     3 999999 [Deltok ikke i runden] 999999       999999 [Deltok ikke i…\n4     10     1      5                          2002           44                \n5     10     2      5                          2007           49                \n6     10     3      5                          2017           59                \n```\n:::\n:::\n\n\nLegg merke til at under hvert variabelnavn står det en liten tekst, f.eks. <dbl> eller <S3: haven_labelled>. Det kan også stå andre ting. dbl betyr at det er en kontinuerlig variabel, mens haven_labelled betyr at det er labler til alle eller noe verdier i variabelen. \n\nEn tilsvarende variant er å bruke *glimpse()* bare på et utvalg variable på tilsvarende måte. Her er et eksempel, men der vi ser på de 10 første variablene. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(norlag[, 1:20])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 33,084\nColumns: 20\n$ ref_nr          <dbl> 5, 5, 5, 10, 10, 10, 12, 12, 12, 15, 15, 15, 18, 18, 1…\n$ round           <dbl> 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, …\n$ iointervjumnd   <dbl+lbl>      5,     11, 999999,      5,      5,      5,   …\n$ iointervjuyr    <dbl+lbl>   2002,   2007, 999999,   2002,   2007,   2017,   …\n$ ioalder         <dbl+lbl>     68,     72, 999999,     44,     49,     59,   …\n$ iolandb         <dbl+lbl>      1,      1,      1,      1,      1,      1,   …\n$ iolandb3        <dbl+lbl>     NA,     NA, 999999,      1,      1,      1,   …\n$ iosvar          <dbl+lbl>      1,      1, 999999,      1,      1,      1,   …\n$ iofodselsyr     <dbl> 1934, 1934, 1934, 1957, 1957, 1957, 1955, 1955, 1955, …\n$ iokjonn         <dbl+lbl> 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,…\n$ iopafyll        <dbl+lbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0,…\n$ iodeltagelse    <dbl+lbl> 5, 5, 5, 1, 1, 1, 2, 2, 2, 5, 5, 5, 3, 3, 3, 4, 4,…\n$ ionorlag1kohort <dbl+lbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,…\n$ iododyr         <dbl+lbl> 9996, 9996, 9996, 9996, 9996, 9996, 9996, 9996, 99…\n$ ssIO_sivil      <dbl+lbl>  2,  2, NA,  4,  4,  4,  2, NA,  2,  4,  4, NA, NA…\n$ hh001c          <dbl+lbl>      1,      1, 999999,      1,      1,      1,   …\n$ hh002           <dbl> 2, 2, 999999, 3, 2, 2, 2, 999999, 2, 1, 1, 999999, 999…\n$ pa001c          <dbl+lbl>      1,      1, 999999,      0,      1,      1,   …\n$ pa002c          <dbl+lbl>     NA,      1, 999999,     NA,      2,      2,   …\n$ pa003           <dbl+lbl>     60,     66, 999999,    996,     57,     67,   …\n```\n:::\n:::\n\n\n\nI denne output'en er den første kollonnen altså variabelnavnene, deretter er det en kollonne som viser hva slags type variabel det er, og deretter de første observasjonene på hver variabel slik at man får et inntrykk av hvordan det ser ut. *glimpse()* gir altså omtrent samme informasjon som *head()*, men er nok mer hensiktsmessig hvis mange variable. \n\n\nFor å se nærmere på en variabel går an å bruke funksjonen `look_for()`, som primært er en søke-funksjon, men det gir også informasjon om variabelen.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlook_for(norlag, \"iokjonn\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n pos variable label     col_type values    \n 10  iokjonn  IOs kjønn dbl+lbl  [1] Mann  \n                                 [2] Kvinne\n```\n:::\n:::\n\nI output fremgår det at dette er den 10'ende variabelen, inneholder informasjonen \"IOs kjønn\", er av typen numerisk med tilhørende labler, og verdiene er 1 = Mann og 2 = Kvinne. \n\n\nDet går også an å bare få ut variabel-label med funksjonen `var_label()` slik: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_label(norlag$iokjonn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"IOs kjønn\"\n```\n:::\n:::\n\n\nFor å se labels på *verdiene* bruk **val_labels()**.\n\n::: {.cell}\n\n```{.r .cell-code}\nval_labels(norlag$iokjonn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Mann Kvinne \n     1      2 \n```\n:::\n:::\n\n\n\n### Alternativ: pakken {memisc} og `codebook()`\nMan vil klare seg greit med det vi har vist ovenfor. Men det finnes flere måter å gjøre det på. Pakken {memisc} inneholder en rekke funksjoner for å håndtere surveydata, som vi ikke skal gå nærmere inn på her. Men akkurat funksjonen `codebook()` gir litt mer informativt output enn `look_for()`. \n\nFor å bruke denne må du installere pakken først. I eksempelet nedenfor er pakken ikke lastet med library(), men angitt pakken direkte med `memisc::` først. Dette kan være nyttig hvis man ikke skal bruke noen andre funksjoner fra denne pakken.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmemisc::codebook(norlag$iokjonn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   norlag$iokjonn 'IOs kjønn'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n\n   Values and labels       N Percent\n                                    \n   1 'Mann'            16197    49.0\n   2 'Kvinne'          16887    51.0\n```\n:::\n:::\n\n\nPoenget her er altså bare å få en penere output og litt deskriptiv statistikk samtidig. \n\n\n\n## Søke i datasettet etter variable\nAlle datasett skal komme med en dokumentasjon som sier hva hver variabel inneholder og hvilke verdier som finnes i hver variable, og hva de betyr. Dette leveres gjerne som en separat fil, ganske ofte i pdf eller html format. NSD/Sikt leverer dokumentasjonen for Norlag i html-format. (Ideelt burde det vært i et enkelt maskinlesbart format egnet til å bruke til omkoding og labler for de som ønsker det, men de har valgt en annen løsning). \n\nDu kan søke i dokumentasjonen på samme måte som i andre filer, men det kan være litt knotete. Et godt alternativ er å søke direkte i datasettet. Funksjonen **look_for()** søker både i variabelnavn, verdier og labler. Her er et eksempel for hvordan finne variabler som inneholder ordet \"yrkesinntekt\". Du kan også søke på kortere eller lengre tekststrenger. (Søker du f.eks. bare på \"innt\" eller \"yrke\" så får du opp langt flere variable, så du må kanskje prøve deg litt frem).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlook_for(norlag, \"Yrkesinntekt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n pos variable       label                   col_type values                 \n 353 inwyrkinnt     Yrkesinntekter NorLAG ~ dbl+lbl  [-5000] Value <0 >-5000\n                                                     [5000] Value >0 <5000  \n                                                     [999999999] Mangler da~\n 371 inpartwyrkinnt Partner: yrkesinntekte~ dbl+lbl  [99999996] Filter: IO ~\n                                                     [99999999] Mangler data\n                                                     [999999999] Deltok ikk~\n```\n:::\n:::\n\n\nDet er to variable som inneholder teksten \"yrkesinntekt\". Den første variabelen har posisjon 353 i datasettet og har variabelnavnet inwyrkinnt.  Den andre variabelen har posisjon 371 og har navnet inpartwyrkinnt. Vi fokuserer på den første.\n\nMerk at når labelen avsluttes med ~ (uttales \"tilde\") indikerer det at teksten er avkortet i outputvinduet. Du får opp hele teksten ved å bruke *val_label()* slik: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_label(norlag$inwyrkinnt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Yrkesinntekter NorLAG longitudinell\"\n```\n:::\n:::\n\n\n\n\n## Omkode variable som er labelled  \nNoen ganger vil vi omkode en variabel. Et eksempel er variabelen he104. Her er innholdet i den variabelen. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmemisc::codebook(norlag$he104)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   norlag$he104 'Hvordan vil du beskrive din økonomiske situasjon nå'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n\n   Values and labels                                           N Percent\n                                                                        \n        1 'Veldig romslig'                                  1425     4.3\n        2 'Romslig'                                         8039    24.3\n        3 'Må være forsiktig, men klarer meg'               5152    15.6\n        4 'Problemer med å få pengene til å strekke til'     551     1.7\n        5 'Svært vanskelig økonomisk situasjon'              164     0.5\n      999 'Mangler data'                                     403     1.2\n    99999 'Ikke svart post/web-skjema'                      5158    15.6\n   999999 'Deltok ikke i runden'                           12192    36.9\n```\n:::\n:::\n\n\nLegg merke til at de tre nederste verdiene egentlig er varianter av å mangle data. Disse verdiene skal normalt ikke være med i en videre analyse, men er \"missing\". Vi bør fortelle R at disse verdiene ikke skal tas med videre ved å omkode til NA. \n\nFølgende kode gjør en omkoding til NA. I eksempelet har jeg lagt inn linjeskift for mutate() for å tydeliggjøre de ulike delene. \n\n* Første linje lager en ny variabel he104b som skal inne en kopi av he104. Funksjonen `replace()` tar så utgangspunkt i variabelen he104, og de verdiene som ikke er angitt at skal byttes ut vil beholdes fra denne.  \n* Andre linje sier at hvis variabelen he104 er en av verdiene 999, 99999, eller 999999, så... \n* sier tredje linje at da skal de få verdien NA i stedet. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag %>% \n  mutate(he104b = replace(he104, \n                         he104 %in% c(999, 99999, 999999), \n                         NA)) %>%  \n    select(he104b) %>% \n  memisc::codebook()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   he104b 'Hvordan vil du beskrive din økonomiske situasjon nå'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n\n   Values and labels                                           N Valid Total\n                                                                            \n        1   'Veldig romslig'                                1425   9.3   4.3\n        2   'Romslig'                                       8039  52.4  24.3\n        3   'Må være forsiktig, men klarer meg'             5152  33.6  15.6\n        4   'Problemer med å få pengene til å strekke til'   551   3.6   1.7\n        5   'Svært vanskelig økonomisk situasjon'            164   1.1   0.5\n      999   'Mangler data'                                     0   0.0   0.0\n    99999   'Ikke svart post/web-skjema'                       0   0.0   0.0\n   999999   'Deltok ikke i runden'                             0   0.0   0.0\n       NA M                                                17753        53.7\n```\n:::\n:::\n\n\nLegg merke til at output nå har de omtalte verdiene 0 observasjoner, men lablene finnes i variabelen likevel! Lablene eksisterer altså uavhengig av verdiene i variabelen, men det har kommet en linje til med verdien NA. Det er det det ble omkodet til. \nNå trenger vi jo ikke de lablene vi omkodet, så de kan fjernes helt. Funksjoen `drop_unused_value_labels()` gjør akkurat det det høres ut som. Her er et eksempel: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag %>% \n  select(he104) %>% \n  mutate(he104 = replace(he104, \n                         he104 %in% c(999, 99999, 999999), \n                         NA)) %>%  \n  drop_unused_value_labels() %>% \n  memisc::codebook()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   he104 'Hvordan vil du beskrive din økonomiske situasjon nå'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n\n   Values and labels                                       N Valid Total\n                                                                        \n    1   'Veldig romslig'                                1425   9.3   4.3\n    2   'Romslig'                                       8039  52.4  24.3\n    3   'Må være forsiktig, men klarer meg'             5152  33.6  15.6\n    4   'Problemer med å få pengene til å strekke til'   551   3.6   1.7\n    5   'Svært vanskelig økonomisk situasjon'            164   1.1   0.5\n   NA M                                                17753        53.7\n```\n:::\n:::\n\n\n\n\n### Alternativ: legg til user-specified-na\nEn alternativ fremgangsmåte er mer slik man ville gjort i annen software ved at man definerer disse verdiene som \"missing\", dvs NA. Funksjonen `set_na_values()` definerer hvilke verdier som skal regnes som NA, men uten å endre lablene eller kode om på annen måte. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag %>% \n  select(he104) %>% \n  set_na_values(he104 = c(999, 99999, 999999) ) %>% \n  memisc::codebook()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   he104 'Hvordan vil du beskrive din økonomiske situasjon nå'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n   Missing values: 999, 99999, 999999\n\n   Values and labels                                           N Valid Total\n                                                                            \n        1   'Veldig romslig'                                1425   9.3   4.3\n        2   'Romslig'                                       8039  52.4  24.3\n        3   'Må være forsiktig, men klarer meg'             5152  33.6  15.6\n        4   'Problemer med å få pengene til å strekke til'   551   3.6   1.7\n        5   'Svært vanskelig økonomisk situasjon'            164   1.1   0.5\n      999 M 'Mangler data'                                   403         1.2\n    99999 M 'Ikke svart post/web-skjema'                    5158        15.6\n   999999 M 'Deltok ikke i runden'                         12192        36.9\n```\n:::\n:::\n\n\nI output står det nå en \"M\" mellom verdien og labelen, som angir at dette er \"Missing\". I frekvenstabellen er det nå i prosentueringen skilt mellom *Valid* og *Total*, der missing altså ikke er regnet med blant gyldige verdier. \n\nMen det er ryddigst å fjerne disse missing-verdiene og sette de til NA. Funksjonen `zap_na()` gjør disse verdiene om til NA, altså omkoder alle missingverdiene til NA. Som i forrige variant vil da lablene fremdeles eksistere, men disse kan fjernes på samme måte med `drop_unused_value_labels()`.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag %>% \n  select(he104) %>% \n  set_na_values(he104 = c(999, 99999, 999999) ) %>% \n  zap_missing() %>% \n  drop_unused_value_labels() %>% \n  memisc::codebook()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n\n   he104 'Hvordan vil du beskrive din økonomiske situasjon nå'\n\n--------------------------------------------------------------------------------\n\n   Storage mode: double\n   Measurement: undefined\n\n   Values and labels                                       N Valid Total\n                                                                        \n    1   'Veldig romslig'                                1425   9.3   4.3\n    2   'Romslig'                                       8039  52.4  24.3\n    3   'Må være forsiktig, men klarer meg'             5152  33.6  15.6\n    4   'Problemer med å få pengene til å strekke til'   551   3.6   1.7\n    5   'Svært vanskelig økonomisk situasjon'            164   1.1   0.5\n   NA M                                                17753        53.7\n```\n:::\n:::\n\n\n\n\n## Omkoding av andre verdier\nVi starter med å lagre de endringene som ble testet ut over, og lagrer disse i et nytt datasett som kalles *norlag2* som vi bruker videre i eksemplene. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag2 <- norlag %>% \n  select(he104) %>% \n  mutate(he104 = replace(he104, \n                         he104 %in% c(999, 99999, 999999), \n                         NA)) %>%  \n  drop_unused_value_labels() \n```\n:::\n\n\n\n\n## Konverter variable til et mer ordinært R-format \n\nVi starter med å lagre en kopi av datasettet med endrede labler. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag3 <- norlag2 %>% \n  mutate(he104 = recode(he104, \n                          `1` = 2 ,\n                          `5` = 4,\n                        .combine_value_labels = TRUE) ) %>% \n  add_value_labels(he104 = c(\"Romslig/veldig romslig\" = 2, \n                             \"Problemer/store problemer\" = 4))\n```\n:::\n\n\n\nMen hva skjer når vi skal lage en fin tabell? Vi prøver med {gtsummary} og `tbl_summary()`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nnorlag3 %>% \n  tbl_summary(include = he104)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mecqgxhvuu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#mecqgxhvuu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mecqgxhvuu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mecqgxhvuu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mecqgxhvuu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mecqgxhvuu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mecqgxhvuu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mecqgxhvuu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mecqgxhvuu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mecqgxhvuu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mecqgxhvuu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mecqgxhvuu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mecqgxhvuu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mecqgxhvuu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mecqgxhvuu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecqgxhvuu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mecqgxhvuu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mecqgxhvuu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecqgxhvuu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mecqgxhvuu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecqgxhvuu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mecqgxhvuu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecqgxhvuu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mecqgxhvuu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecqgxhvuu .gt_left {\n  text-align: left;\n}\n\n#mecqgxhvuu .gt_center {\n  text-align: center;\n}\n\n#mecqgxhvuu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mecqgxhvuu .gt_font_normal {\n  font-weight: normal;\n}\n\n#mecqgxhvuu .gt_font_bold {\n  font-weight: bold;\n}\n\n#mecqgxhvuu .gt_font_italic {\n  font-style: italic;\n}\n\n#mecqgxhvuu .gt_super {\n  font-size: 65%;\n}\n\n#mecqgxhvuu .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#mecqgxhvuu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mecqgxhvuu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mecqgxhvuu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mecqgxhvuu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mecqgxhvuu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mecqgxhvuu .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 33,084&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>N = 33,084</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Hvordan vil du beskrive din økonomiske situasjon nå</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9,464 (62%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,152 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">715 (4.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17,753</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nTabellen vises altså uten lablene! Noe av poenget med å ha labler var jo å at det skal syens... Siden mange funksjoner i R i utgangspunktet ikke er laget for labler er det rett og slett ikke støttet.  \n\nMen vi kan gjøre om variabelen med `as_factor()`. Gjør om lablene til faktor-nivåer og så lage en tabell med den endrede variabelen. \n(OBS! funskjonen `as_factor()` gjør bare nesten det samme. `as_factor()` er laget bl.a. for å håndtere labler, mens `as_factor()` ikke gjør det).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag3 %>% \n  mutate(he104 = as_factor(he104)) %>% \n  gtsummary::tbl_summary(include = he104)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"rxzxusagst\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#rxzxusagst .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rxzxusagst .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rxzxusagst .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rxzxusagst .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rxzxusagst .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rxzxusagst .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rxzxusagst .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rxzxusagst .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rxzxusagst .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rxzxusagst .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rxzxusagst .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rxzxusagst .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rxzxusagst .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rxzxusagst .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rxzxusagst .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rxzxusagst .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rxzxusagst .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rxzxusagst .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rxzxusagst .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rxzxusagst .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rxzxusagst .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rxzxusagst .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rxzxusagst .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rxzxusagst .gt_left {\n  text-align: left;\n}\n\n#rxzxusagst .gt_center {\n  text-align: center;\n}\n\n#rxzxusagst .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rxzxusagst .gt_font_normal {\n  font-weight: normal;\n}\n\n#rxzxusagst .gt_font_bold {\n  font-weight: bold;\n}\n\n#rxzxusagst .gt_font_italic {\n  font-style: italic;\n}\n\n#rxzxusagst .gt_super {\n  font-size: 65%;\n}\n\n#rxzxusagst .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#rxzxusagst .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rxzxusagst .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rxzxusagst .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rxzxusagst .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rxzxusagst .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rxzxusagst .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 33,084&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>N = 33,084</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Hvordan vil du beskrive din økonomiske situasjon nå</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Romslig/veldig romslig</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9,464 (62%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Må være forsiktig, men klarer meg</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,152 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Problemer/store problemer</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">715 (4.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17,753</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n\n## Hvordan gjøre alt i en fei: alle variable samtidig \n\n\nFor NorLAG er det noen missingverdier som er definert på tvers av hele datasettet. Se dokumentasjon her: https://norlag.nsd.no/filterverdier \nÅ gjøre de operasjonene vi gjorde over for hver enkelt av de over 400 variablene er utrolig arbeidskrevende og drit kjedelig. Så det gidder vi ikke. Men å omkode alle variable i et helt datasett krever litt mer avanserte operasjoner. Her bruker vi `across()` som angir at vi skal gjøre samme operasjon på de nærere angitte variablene. Vi kan enten gi en liste med variabelnavn, eller sette et krav om at variablene skal være av en viss type, starte med visse bokstaver eller tegn osv. I eksempelet nedenfor angir vi bare at variabelene skal være av typen 'labelled', noe de aller fleste er. Missing-verdiene i datasettet er jo felles for alle variable, så da kan vi bruke replace() og sette disse til NA. Her er et eksempel:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag4 <- norlag %>% \n  mutate(across( where(is.labelled) ,  ~replace(., \n                                        . %in% c(997, 998, 999, 99999, 999999), \n                                        NA))) %>%  \n  drop_unused_value_labels()                                           \n```\n:::\n\n\nI mutate-setningen skjer følgende: \n\n* `across()` sier at vi skal gjøre det samme for flere variable, spesifisert med `where(is.labelled)`. \n* for disse skal vi bruke `replace()`, angitt ved `~replace()`\n* inni parentesen angis . som hver av de variablene som er plukket ut i `across()`. Så for disse variablene skal det byttes ut verdier\n* neste linje starter med `.`, som igjen henviser til de samme variablen, og hvis de har en av de opplistede verdiene\n* i så fall får de ny verdi `NA`\n\n\nDermed er samtlige labelled-variable omkodet på denne måten i en fei. \n\nDa kan vi lage en tabell på nytt. Her får vi samme problem med at lablene ikke synes, men missing-verdiene er i hvetr fall ryddet opp i.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag4 %>% \n  gtsummary::tbl_summary(include = he104)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"tslikbnzrd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#tslikbnzrd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tslikbnzrd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tslikbnzrd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tslikbnzrd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tslikbnzrd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tslikbnzrd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tslikbnzrd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tslikbnzrd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tslikbnzrd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tslikbnzrd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tslikbnzrd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tslikbnzrd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tslikbnzrd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tslikbnzrd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tslikbnzrd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tslikbnzrd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tslikbnzrd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tslikbnzrd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tslikbnzrd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tslikbnzrd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tslikbnzrd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tslikbnzrd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tslikbnzrd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tslikbnzrd .gt_left {\n  text-align: left;\n}\n\n#tslikbnzrd .gt_center {\n  text-align: center;\n}\n\n#tslikbnzrd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tslikbnzrd .gt_font_normal {\n  font-weight: normal;\n}\n\n#tslikbnzrd .gt_font_bold {\n  font-weight: bold;\n}\n\n#tslikbnzrd .gt_font_italic {\n  font-style: italic;\n}\n\n#tslikbnzrd .gt_super {\n  font-size: 65%;\n}\n\n#tslikbnzrd .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#tslikbnzrd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tslikbnzrd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tslikbnzrd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tslikbnzrd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tslikbnzrd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tslikbnzrd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 33,084&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>N = 33,084</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Hvordan vil du beskrive din økonomiske situasjon nå</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,425 (9.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">8,039 (52%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,152 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">551 (3.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    5</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">164 (1.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17,753</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n\nVi kan selvfølgelig endre til factor som gjort over, men da får vi igjen et problem med å gjøre det en variabel om gangen. Igjen: det gidder vi ikke. I stedet bruker vi en enkel funksjon som fikser biffen for hele datasettet, nemlig `unlabelled()`.  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnorlag4 %>% \n  unlabelled() %>% \n  gtsummary::tbl_summary(include = he104)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"gaezmaabla\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#gaezmaabla .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gaezmaabla .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gaezmaabla .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gaezmaabla .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gaezmaabla .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gaezmaabla .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gaezmaabla .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gaezmaabla .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gaezmaabla .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gaezmaabla .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gaezmaabla .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gaezmaabla .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gaezmaabla .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gaezmaabla .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gaezmaabla .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gaezmaabla .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gaezmaabla .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gaezmaabla .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gaezmaabla .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gaezmaabla .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gaezmaabla .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gaezmaabla .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gaezmaabla .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gaezmaabla .gt_left {\n  text-align: left;\n}\n\n#gaezmaabla .gt_center {\n  text-align: center;\n}\n\n#gaezmaabla .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gaezmaabla .gt_font_normal {\n  font-weight: normal;\n}\n\n#gaezmaabla .gt_font_bold {\n  font-weight: bold;\n}\n\n#gaezmaabla .gt_font_italic {\n  font-style: italic;\n}\n\n#gaezmaabla .gt_super {\n  font-size: 65%;\n}\n\n#gaezmaabla .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#gaezmaabla .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gaezmaabla .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gaezmaabla .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gaezmaabla .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gaezmaabla .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gaezmaabla .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 33,084&lt;/strong&gt;&lt;sup class=&quot;gt_footnote_marks&quot;&gt;1&lt;/sup&gt;\"><strong>N = 33,084</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Hvordan vil du beskrive din økonomiske situasjon nå</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Veldig romslig</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,425 (9.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Romslig</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">8,039 (52%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Må være forsiktig, men klarer meg</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,152 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Problemer med å få pengene til å strekke til</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">551 (3.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Svært vanskelig økonomisk situasjon</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">164 (1.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17,753</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nOBS! Unlabelled endrer alle labelled-variablene. Det er ikke sikkert at vi vil det. Spesielt gjelder det at det kan være andre labler knyttet til variable som skal være kontinuerlige. Men: hvis man har gjort en god opprydning i datasetet i forkant, med de omkodinger som trengs (det må nok gjøres en for en variabel), så er dette ganske greit. \n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}